I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Chapters/chapter1.rpy", line 24, in script
    diseased dog "bork bork *whimper"
Exception: Sayer 'diseased' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Chapters/chapter1.rpy", line 24, in script
    diseased dog "bork bork *whimper"
  File "/Applications/renpy-8.1.3-sdk/renpy/ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Applications/renpy-8.1.3-sdk/renpy/ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'diseased' is not defined.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.1.3.23091805
HorrorGame 1.0
Sun Jan 14 13:31:14 2024
